// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehtrhgssqckrszdlffjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVodHJoZ3NzcWNrcnN6ZGxmZmpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzA5MDEsImV4cCI6MjA1ODI0NjkwMX0.1CBOZPHtrEuBkQH-i1dLvZ8RKG2Md2aUrhHR445KNBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);